# Generated by Django 3.2.6 on 2021-08-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_cart',
            unique_together={('product', 'cart')},
        ),
    ]
